apiVersion: v1
kind: Service
metadata:
  name: clb-tasky-app-service
  labels:
    app: tasky-app-service
spec:
  type: LoadBalancer  # Regular k8s Service manifest with type as LoadBalancer
  selector:
    app: tasky-app    
  ports:
  - port: 80
    targetPort: 8080
